# Configuration of py.test
[pytest]
addopts=-v
        -n 2
        --durations=20

# Do not run tests in the build folder
norecursedirs= build

# Use 85 as max line length in PEP8 test.
pep8maxlinelength=85

# PEP-8 The following are ignored:
# E731 do not assign a lambda expression, use a def
# E402 module level import not at top of file

pep8ignore=* E731 \
           * E402 \